
package com.ph.socialsecurityvisualization.entitiy;

/**
 * Auto Generated By Hap Code Generator
 **/

import java.math.BigDecimal;

/**
 * The type Co editor.
 *
 * @author Jesse
 */

public class InsureUnitTrend {

    private Long insureId;


    private Long insureUnit;

    private Long insureCancel;
    private String insureDate;
    private BigDecimal yearOnYear;
    private BigDecimal monthOnMonth;

    public Long getInsureId() {
        return insureId;
    }

    public void setInsureId(Long insureId) {
        this.insureId = insureId;
    }

    public Long getInsureUnit() {
        return insureUnit;
    }

    public void setInsureUnit(Long insureUnit) {
        this.insureUnit = insureUnit;
    }

    public Long getInsureCancel() {
        return insureCancel;
    }

    public void setInsureCancel(Long insureCancel) {
        this.insureCancel = insureCancel;
    }

    public String getInsureDate() {
        return insureDate;
    }

    public void setInsureDate(String insureDate) {
        this.insureDate = insureDate;
    }

    public BigDecimal getYearOnYear() {
        return yearOnYear;
    }

    public void setYearOnYear(BigDecimal yearOnYear) {
        this.yearOnYear = yearOnYear;
    }

    public BigDecimal getMonthOnMonth() {
        return monthOnMonth;
    }

    public void setMonthOnMonth(BigDecimal monthOnMonth) {
        this.monthOnMonth = monthOnMonth;
    }
}
